### ISSUE TITLE
It is unclear what permissions are needed for which actions

### ISSUE THREAD

**Issue by Bertg** [crowdin/github-action#230]
**Describe the bug**

I've been trying to set up download of translations for my project. As a security conscious person, I wanted to create a token with minimal permissions for this task. I could not find any documentation on how to do that, but the permissions seems very self explanatory.

```
     - name: ⤵️ Download translation from Crowdin
         uses: crowdin/github-action@v1
         with:
           upload_sources: false
           upload_translations: false
           download_translations: true
           create_pull_request: false
           push_translations: false
         env:
           CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
```

I've tried several iterations of new tokens, each hitting the same issue:

```
+ set -e
+ set -- --no-progress --no-colors
+ '['  '=' true ]
+ '[' -n 1 ]
+ set -- --no-progress --no-colors --verbose --debug
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' false '=' true ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ '[' true '=' true ]
+ download_translations --no-progress --no-colors --verbose --debug
+ '[' -n  ]
+ '[' -n  ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ '[' -n  ]
+ echo 'DOWNLOAD TRANSLATIONS'
+ crowdin download --no-progress --no-colors --verbose --debug
STARTING CROWDIN ACTION
DOWNLOAD TRANSLATIONS
✔️  Fetching project info
✔️  Building ZIP archive with the latest translations
❌ Building translations
java.lang.RuntimeException: Failed to build translation. Please contact our support team for help
	at com.crowdin.cli.utils.console.ConsoleSpinner.execute(ConsoleSpinner.java:29)
	at com.crowdin.cli.commands.actions.DownloadAction.buildTranslation(DownloadAction.java:413)
	at com.crowdin.cli.commands.actions.DownloadAction.download(DownloadAction.java:346)
	at com.crowdin.cli.commands.actions.DownloadAction.lambda$act$7(DownloadAction.java:206)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.crowdin.cli.commands.actions.DownloadAction.act(DownloadAction.java:184)
	at com.crowdin.cli.commands.actions.DownloadAction.act(DownloadAction.java:47)
	at com.crowdin.cli.commands.picocli.GenericActCommand.run(GenericActCommand.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.crowdin.cli.commands.picocli.PicocliRunner.execute(PicocliRunner.java:39)
	at com.crowdin.cli.Cli.main(Cli.java:16)
Caused by: java.lang.RuntimeException: You do not have permission to view/edit project with provided id
	at com.crowdin.cli.client.CrowdinClientCore$1.<init>(CrowdinClientCore.java:35)
	at com.crowdin.cli.client.CrowdinClientCore.<clinit>(CrowdinClientCore.java:28)
	at com.crowdin.cli.client.Clients.getProjectClient(Clients.java:67)
	at com.crowdin.cli.commands.picocli.ActCommandWithFiles.getClient(ActCommandWithFiles.java:30)
	at com.crowdin.cli.commands.picocli.ActCommandWithFiles.getClient(ActCommandWithFiles.java:11)
	at com.crowdin.cli.commands.picocli.GenericActCommand.run(GenericActCommand.java:37)
	... 10 more

╭──────────────────────────────────────────────────────────────────────────────╮
│           New version of Crowdin CLI is available! 3.19.4 -> 4.0.0           │
├──────────────────────────────────────────────────────────────────────────────┤
│      Changelog: https://github.com/crowdin/crowdin-cli/releases/latest       │
│                    Please update for the best experience!                    │
╰──────────────────────────────────────────────────────────────────────────────╯
##[debug]Docker Action run completed with exit code 1
##[debug]Set output pull_request_url = 
##[debug]Set output pull_request_number = 
##[debug]Finishing: ⤵️ Download translation from Crowdin
```

Out of frustration I created a token with full read/write permissions.

**Expected behavior**

I think it would be reasonable to be able to download translations with ONLY the read permission on translations activated. This is clearly not the case.

**Comment by Bertg** [comment]
I'm actually not sure if this issue needs to be reported here, or if this is a CLI issue...

**Comment by RandomEngy** [comment]
It appears that the instructions are for creating a "Classic" token and not the new fine-grained access tokens. Would be nice to have instructions for the new PAT type as well.

**Comment by andrii-bodnar** [comment]
The read permission isn't enough for this, because the translation download triggers the Crowdin project build, which affects the project state (the latest build will contain new translations).

The Action/CLI can be used for different cases, so it depends very much on the exact case which permissions are needed for these cases. For the usual uploading of source files and downloading of translations, the following token permissions should be sufficient:

- Projects (List, Get, Create, Edit)
- Translation status
- Source files & strings
- Translations

![Screenshot 2024-06-11 at 15 10 34](https://github.com/crowdin/github-action/assets/29282228/aad6d280-9fc9-4ddc-8e15-e1425ef48fac)

**Comment by Bertg** [comment]
Honestly, I think this is very counter intuitive and defeats the purpose entirely.

If I want to download the translations (and only that), I should not be able to update them. I for sure should also not be able to update the projects or change the source files. 

Basically if my build automations would get compromised, that token would allow an attacker to grief my project. 

Honestly, I think this should be considered a security issue to be honest.
