### ISSUE TITLE
File upload failed

### ISSUE THREAD

**Issue by sy-records** [crowdin/github-action#238]
**Describe the bug**
see https://github.com/docsifyjs/docsify/actions/runs/10010601939/job/27688678207#step:4:237

themes.md: https://github.com/docsifyjs/docsify/blob/develop/docs/themes.md

```
java.lang.RuntimeException: File 'develop/themes.md'
	at com.crowdin.cli.commands.picocli.ExitCodeExceptionMapper.remap(ExitCodeExceptionMapper.java:19)
	at com.crowdin.cli.commands.actions.UploadSourcesAction.lambda$act$8(UploadSourcesAction.java:229)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: Wrong parameters: 
<key: storageId, code: fileInvalid, message: An unknown error occurred while importing the file.>
	at com.crowdin.cli.client.CrowdinClientCore.executeRequest(CrowdinClientCore.java:118)
	at com.crowdin.cli.client.CrowdinClientCore.executeRequestWithPossibleRetries(CrowdinClientCore.java:85)
	at com.crowdin.cli.client.CrowdinProjectClient.updateSource(CrowdinProjectClient.java:262)
	at com.crowdin.cli.commands.actions.UploadSourcesAction.lambda$act$8(UploadSourcesAction.java:206)
	... 5 more
java.lang.RuntimeException: Current execution finished with errors
	at com.crowdin.cli.commands.actions.UploadSourcesAction.act(UploadSourcesAction.java:349)
	at com.crowdin.cli.commands.actions.UploadSourcesAction.act(UploadSourcesAction.java:39)
	at com.crowdin.cli.commands.picocli.GenericActCommand.run(GenericActCommand.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:[241](https://github.com/docsifyjs/docsify/actions/runs/10010601939/job/27688678207#step:4:242)9)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:[242](https://github.com/docsifyjs/docsify/actions/runs/10010601939/job/27688678207#step:4:243)1)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at com.crowdin.cli.commands.picocli.PicocliRunner.execute(PicocliRunner.java:38)
	at com.crowdin.cli.Cli.main(Cli.java:16)
```

**To Reproduce**
1. Crowdin GitHub Action configuration https://github.com/docsifyjs/docsify/actions/runs/10010601939/workflow
2. `crowdin.yml` file content. 
3. Information about workflow (OS, steps, etc.) https://github.com/docsifyjs/docsify/blob/develop/.github/crowdin/crowdin-push.yml

**Expected behavior**

themes.md uploaded normally.

**Comment by sy-records** [comment]
No.

<img width="412" alt="image" src="https://github.com/user-attachments/assets/56eb98eb-6322-4348-95eb-8c5a36e9a6b0">


```json
{
    "success": true,
    "data": {
        "progress": 0,
        "in_progress": false,
        "info": {
            "code": 0,
            "note": "Revision Domain Exception: An unknown error occurred while importing the file."
        }
    },
    "version": "9"
}
```

**Comment by andrii-bodnar** [comment]
@sy-records thank you!

It seems like it's an issue related to the file import process, not the GH Action itself. 

Please [contact](https://crowdin.com/contacts) our Customer Success team for further investigation.

**Comment by sy-records** [comment]
Fixed. Thank you.
